version: "3"

services:
  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      #指定data路徑(主資料)
      - d:/docker-volumes/elasticsearch/data:/usr/share/elasticsearch/data
      #指定logs路徑(日誌)
      - d:/docker-volumes/elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      #指定外部來源用
      - d:/docker-volumes:/usr/share/out-volumes
    ports:
      - "5000:5000"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  # filebeat:
  #   build: filebeat/
  #   volumes:
  #     - ./filebeat/config:/etc/filebeat
  #     - D:\MoneyInWebLog:/logs
  #   networks:
  #     - elk
  #   depends_on:
  #     - logstash
  #   restart: unless-stopped

networks:
  elk:
    driver: bridge
